### PR TITLE
Move point when executing evil-cp-change

### PR DESCRIPTION
**Pull request by yyoncho**

### CODE REVIEW

**Comment by yyoncho** [comment]
ping

**Comment by duianto** [comment]
Confirmed, this resolves: #70
Example from #70:
```
(|foo  "bar") 
```
- With `evil-cleverparens-mode` enabled
- Pressing `ci"` results in:

Before:
```
(|foo "")
```
After:
```
(foo "|") 
```

**Comment by yyoncho** [comment]
ping?

**Comment by duianto** [comment]
The author doesn't seem to be very active on github, the last activity seems to have been in sept 2018.
https://github.com/luxbock

And the latest commit occurred: `Jul 18, 2017`
https://github.com/luxbock/evil-cleverparens/commits/master

**Pull request merged**
